#!/bin/bash

#export PATH=/usr/local/opt/bison/bin:$PATH
export YACC=/usr/local/opt/bison/bin/yacc

## Set Java's home directory
export JAVA_HOME="$(/usr/libexec/java_home -v 9)"

brew_opt=/usr/local/opt

# Get Homebrew-managed non-linked utils on the path
PATH="$brew_opt/texinfo/bin:$PATH"
PATH="$brew_opt/qt/bin:$PATH"

# Set up dependencies that are not symbolically linked by Homebrew
LDFLAGS=""
CPPFLAGS=""
LDFLAGS="$LDFLAGS -L${brew_opt}/readline/lib"
CPPFLAGS="$CPPFLAGS -I${brew_opt}/readline/include"
CPPFLAGS="$CPPFLAGS -I${brew_opt}/sundials27/include"
LDFLAGS="$LDFLAGS -L${brew_opt}/sundials27/lib"
export LDFLAGS
export CPPFLAGS


PKG_CONFIG_PATH=""
# Add ICU4C to the pkg-config path
PKG_CONFIG_PATH="$PKG_CONFIG_PATH:${brew_opt}/icu4c/lib/pkgconfig"
export PKG_CONFIG_PATH


../../octave/configure --prefix=/tmp/test-octave \
  --without-x \
  --disable-no-undefined \
  --without-osmesa \
  --without-fltk \
  --without-qt \
  --with-hdf5-includedir=$brew_opt/hdf5/include \
  --with-hdf5-libdir=$brew_opt/hdf5/lib \
  --with-blas="-L${brew_opt}/veclibfort/lib -lvecLibFort" \
  | tee config.out
